name: DAST Scan on ZAP

on:
  workflow_run:
    workflows: ["Deploy on AWS Server"]
    types:
      - completed

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
        - name: Upload zap Scan Results
          run: |
            scp -o StrictHostKeyChecking=no -i ~/.ssh/MyKeyPair.pem ec2-user@${{ env.EC2_IP }}:/home/ec2-user/ZAP_2.14.0/zap_scan_results.json ./zap_scan_results.json || { echo "SCP failed"; exit 1; }

        - name: Verify Uploaded File
          run: |
            if [ -f ./zap_scan_results.json ]; then
                echo "Scan results uploaded successfully."
            else
                echo "Failed to upload scan results."
                exit 1
            fi

        - name: Upload zap Scan Results as Artifact
          uses: actions/upload-artifact@v3
          with:
            name: zap-scan-results
            path: ./zap_scan_results.json
