name: Deploy Django App

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lonewolfrex/ubuntu  # Update with your Docker Hub username and image name

      - name: Deploy to server
        run: |
          ssh user@your-server-ip "docker pull your-dockerhub-username/your-image-name:latest && docker run -d -p 8084:8000 lonewolfrex/ubuntu"
